---
language: ruby
cache: bundler
services:
  - postgresql
rvm:
  - 2.7.4
before_install:
  - gem install bundler -v 2.2.28
script:
  - cd spec/apps/dummy
  - RAILS_ENV=test bundle exec rails db:drop db:create db:migrate
  - cd ../../..
  - bundle exec rspec --backtrace
